const getters = {
   tag: state => state.tags.tag,
   website: state => state.common.website,
   userInfo: state => state.user.userInfo,
   theme: state => state.common.theme,
   themeName: state => state.common.themeName,
   isShade: state => state.common.isShade,
   isCollapse: state => state.common.isCollapse,
   keyCollapse: (state, getters) => getters.screen > 0 ? getters.isCollapse : false,
   screen: state => state.common.screen,
   isLock: state => state.common.isLock,
   isFullScren: state => state.common.isFullScren,
   lockPasswd: state => state.common.lockPasswd,
   processArr: state => state.common.processArr,
   patientMessage: state => state.allPatients.patientMessage,
   nurseIndexFlag: state => state.allPatients.nurseIndexFlag,
   //   所有文章
   all_article: state => state.personalSummary.all_article,
   per_article: state => state.personalSummary.per_article,
   ect_article: state => state.personalSummary.ect_article,

   tagList: state => state.tags.tagList,
   tagWel: state => state.tags.tagWel,
   access_token: state => state.user.access_token,
   refresh_token: state => state.user.refresh_token,
   expires_in: state => state.user.expires_in,
   roles: state => state.user.roles,
   permissions: state => state.user.permissions,
   menu: state => state.user.menu,
   menuAll: state => state.user.menuAll,
   logsList: state => state.logs.logsList,
   nurse_patients: state => state.nurse.nurse_patients,
   dep_patients: state => state.matron.dep_patients,
   all_patients: state => state.allPatients.all_patients,
   disable: state => state.common.disable,
   logsLen: state => state.logs.logsList.length || 0,
   logsFlag: (state, getters) => getters.logsLen === 0
}
export default getters
